name: infra

on:
  pull_request:
    paths: ["infra/**"]
  push:
    branches: ["main"]
    paths: ["infra/**"]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: "true"
      TF_VAR_groq_api_key: ${{ secrets.GROQ_API_KEY }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_qdrant_url: ${{ secrets.QDRANT_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Terraform fmt
        run: terraform -chdir=infra/envs/dev fmt -check -recursive

      - name: Terraform init
        run: terraform -chdir=infra/envs/dev init

      - name: Terraform validate
        run: terraform -chdir=infra/envs/dev validate

      - name: Terraform plan
        run: terraform -chdir=infra/envs/dev plan

      - name: Terraform apply (main only)
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=infra/envs/dev apply -auto-approve
